CREATE TABLE dbo.USUARIO (
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    IDADE INT NOT NULL,
    CPF VARCHAR(15) NOT NULL UNIQUE
                
);

CREATE TABLE dbo.MUSICA (
    ID INT IDENTITY(1, 1) PRIMARY KEY, 
    TITULO VARCHAR(150),
    ARTISTA VARCHAR(100),              
    DURACAO TIME,
    GENERO VARCHAR(150)
);

CREATE TABLE dbo.PLAYLIST(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    NOMEPLAYLIST VARCHAR(150),
    PUBLICA BIT DEFAULT 1,
    DATACRIACAO DATETIME2 DEFAULT SYSUTCDATETIME(),
    USUARIO_ID INT NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES dbo.USUARIO(ID)
);

CREATE TABLE dbo.PLAYLIST_MUSICA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    PLAYLIST_ID INT FOREIGN KEY REFERENCES dbo.PLAYLIST(ID),
    MUSICA_ID INT FOREIGN KEY REFERENCES dbo.MUSICA(ID)
);
